### ISSUE TITLE
Question - How are out of order SSDP message handled?

### ISSUE THREAD

**Issue by The-Futurist** [wibosco/SSDPDiscovery-Example#2]
I read your[ in-depth article](https://williamboles.me/discovering-whats-out-there-with-ssdp/) on SSDP on your blog but I have a question, what is the suggested policy for dealing with a situation whereby a device is already online as our app starts up and:

1. It passively announced itself at time T = 0.
2. App starts at time T = 10. (So never saw 1.)
3. App probes for devices at time T = 20.
4. Device responds to probe at time T = 21 - alive msg
5. Device goes offline right afterwards, at time T = 22 - byebye msg
6. App sees the byebye before it sees the alive.
7. App see the alive after it sees the byebye

App thinks the device online but it is not.

Is it sensible to ignore byebye until after we've received an actively probed alive msg?

I've done SSDP and UPnP work some years ago for .Net and I'm just thinking of resuming this when this question came up!

Thanks

**Comment by wibosco** [comment]
@Korporal sorry, don't know how I missed this. 

That is a tricky one. I suspose that even if you ignore the byebye, you still end up thinking that the device is alive when it's offline because of the late arriving alive message.

What do you do with a device once you find it?
