### ISSUE TITLE
Socket Error on certain devices

### ISSUE THREAD

**Issue by tiagomartinho** [wibosco/SSDPDiscovery-Example#3]
Hi William,

Thank you for the project and the awesome blog post!

I've encountered an error while testing the example.

I was only able to get it working on an iPhone SE with iOS 14.4

On both iPad Air 4 with iOS 14.6 and iPhone XS Max with iOS 14.5.1 I get the following error: 
SSDP-Example[402:7547] Encountered socket error: The operation couldn’t be completed. (SSDP_Example.UDPSocketError error 0.)

I added the Local Network Usage Description and disabled App Transport Security.

Any ideas why the error is occurring?

Thank you
Tiago

**Comment by tiagomartinho** [comment]
I think the problem derives from the lack of the com.apple.developer.networking.multicast restricted entitlement.

https://developer.apple.com/news/?id=0oi77447

**Comment by wibosco** [comment]
@tiagomartinho thanks for looking into this and sharing the Apple link
