### ISSUE TITLE
iOS16 issue

### ISSUE THREAD

**Issue by nobody755** [wibosco/SSDPDiscovery-Example#9]
This does not work anymore on iOS16 devices (but works on simulator).
Got this error : Encountered socket error: 
The operation couldn’t be completed. (SSDP_Example.UDPSocketError error 0.)

Any ideas?

**Comment by wibosco** [comment]
@nobody755 since I wrote this, Apple has introduced constraints around apps searching the users local network. 

Have you requested permission from Apple for multicasting? See https://developer.apple.com/news/?id=0oi77447 for more details
